"""Pluggable vector store contracts for semantic RAG."""

from .pipeline import (
    SUPPORTED_BACKENDS,
    VectorHealth,
    VectorHit,
    VectorQuery,
    VectorRebuildResult,
    VectorRecord,
    VectorSyncResult,
    VectorWriteResult,
    active_source_hash_count,
    active_source_record_count,
    delete_by_filter,
    healthcheck,
    hnsw_manifest_path,
    local_index_path,
    local_store_path,
    query,
    record_from_embedding,
    rebuild_from_files,
    replace_records,
    source_records,
    sync_source_records,
    sync_records,
    upsert,
)

__all__ = [
    "SUPPORTED_BACKENDS",
    "VectorHealth",
    "VectorHit",
    "VectorQuery",
    "VectorRebuildResult",
    "VectorRecord",
    "VectorSyncResult",
    "VectorWriteResult",
    "active_source_hash_count",
    "active_source_record_count",
    "delete_by_filter",
    "healthcheck",
    "hnsw_manifest_path",
    "local_index_path",
    "local_store_path",
    "query",
    "record_from_embedding",
    "rebuild_from_files",
    "replace_records",
    "source_records",
    "sync_source_records",
    "sync_records",
    "upsert",
]
