"""Pluggable vector store contracts for semantic RAG."""

from .pipeline import (
    SUPPORTED_BACKENDS,
    IMPLEMENTED_BACKENDS,
    EXPERIMENTAL_BACKENDS,
    VectorHealth,
    VectorHit,
    VectorQuery,
    VectorRebuildResult,
    VectorRecord,
    VectorSyncResult,
    VectorWriteResult,
    delete_by_filter,
    healthcheck,
    query,
    record_from_embedding,
    rebuild_from_files,
    replace_records,
    sync_records,
    upsert,
)

__all__ = [
    "SUPPORTED_BACKENDS",
    "IMPLEMENTED_BACKENDS",
    "EXPERIMENTAL_BACKENDS",
    "VectorHealth",
    "VectorHit",
    "VectorQuery",
    "VectorRebuildResult",
    "VectorRecord",
    "VectorSyncResult",
    "VectorWriteResult",
    "delete_by_filter",
    "healthcheck",
    "query",
    "record_from_embedding",
    "rebuild_from_files",
    "replace_records",
    "sync_records",
    "upsert",
]
