"""Reader-payoff review and finalized craft-history services."""

from .contracts import (
    APPROVED_BASELINE_PATH,
    MARKET_PROFILE_IDS,
    PLATFORM_DEVIATION_POLICIES,
    QUALITY_STRICTNESS,
    STORY_PHASE_IDS,
    StyleBaselineApprovalResult,
    approve_style_baseline,
    compile_effective_quality_contract,
    compact_effective_quality_contract,
    infer_story_phase,
)
from .editorial_patterns import (
    PATTERN_REGISTRY,
    EditorialPatternRegistryResult,
    editorial_pattern_observations,
    editorial_patterns_for_task,
    pattern_registry_status,
    rebuild_editorial_pattern_registry,
    refresh_editorial_pattern_registry,
    transition_editorial_pattern,
    truncate_editorial_pattern_registry,
)
from .history import build_structure_observation, record_quality_history, truncate_quality_history
from .review import (
    ReaderPayoffTaskResult,
    ReaderPayoffValidateResult,
    payoff_review_required_reasons,
    reader_payoff_review_status,
    reader_payoff_task,
    reader_payoff_task_is_current,
    reader_payoff_validate,
)

__all__ = [
    "APPROVED_BASELINE_PATH",
    "PATTERN_REGISTRY",
    "EditorialPatternRegistryResult",
    "MARKET_PROFILE_IDS",
    "PLATFORM_DEVIATION_POLICIES",
    "QUALITY_STRICTNESS",
    "ReaderPayoffTaskResult",
    "ReaderPayoffValidateResult",
    "STORY_PHASE_IDS",
    "StyleBaselineApprovalResult",
    "approve_style_baseline",
    "build_structure_observation",
    "compile_effective_quality_contract",
    "compact_effective_quality_contract",
    "infer_story_phase",
    "editorial_pattern_observations",
    "editorial_patterns_for_task",
    "pattern_registry_status",
    "payoff_review_required_reasons",
    "reader_payoff_review_status",
    "reader_payoff_task",
    "reader_payoff_task_is_current",
    "reader_payoff_validate",
    "rebuild_editorial_pattern_registry",
    "refresh_editorial_pattern_registry",
    "record_quality_history",
    "transition_editorial_pattern",
    "truncate_editorial_pattern_registry",
    "truncate_quality_history",
]
